create table if not exists public.contact_messages (
 id bigint generated by default as identity primary key,
 email text not null,
 name text,
 category text not null default 'general',
 message text not null,
 created_at timestamptz not null default now()
);
create index if not exists contact_messages_created_at_idx on public.contact_messages(created_at desc);
-- Supabase Auth handles passwords, verification and password recovery.
-- Keep the service-role key server-only and never put it in index.html.
